# Generated by Django 5.0.6 on 2024-07-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_dscription_remove_item_name_item_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='college_school',
        ),
        migrations.RemoveField(
            model_name='item',
            name='elementary_school',
        ),
        migrations.RemoveField(
            model_name='item',
            name='junior_highschool',
        ),
        migrations.RemoveField(
            model_name='item',
            name='senior_highschool',
        ),
    ]
